### ISSUE TITLE
Installation issue due to dependencies Numpy, Numba

### ISSUE THREAD

**Issue by abhishek-tcs-rni** [facebookresearch/sound-spaces#123]
Hello, 

Following the [given steps](https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md) for installation on an Ubuntu 20.04.1 desktop, at the steps for [`habitat-sim`](https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md#install-dependences-habitat-labhabitat-sim), for the last given command:
```
python setup.py install --headless --audio
```
the output stops at : 
```
.....
Extracting habitat_sim-0.2.2-py3.9-linux-x86_64.egg to /home/$USER/anaconda3/envs/sound_spaces/lib/python3.9/site-packages
Adding habitat-sim 0.2.2 to easy-install.pth file

Installed /home/$USER/anaconda3/envs/sound_spaces/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-linux-x86_64.egg
Processing dependencies for habitat-sim==0.2.2
Searching for tqdm
Reading https://pypi.org/simple/tqdm/
.....

Installed /home/$USER/anaconda3/envs/sound_spaces/lib/python3.9/site-packages/GitPython-3.1.32-py3.9.egg
Searching for attrs>=19.1.0
Reading https://pypi.org/simple/attrs/
.....

Installed /home/$USER/anaconda3/envs/sound_spaces/lib/python3.9/site-packages/attrs-23.1.0-py3.9.egg
error: numpy 1.25.1 is installed but numpy<1.25,>=1.21 is required by {'numba'}
```
where `$USER` is username and `.....` denotes unrelated output. Also, here conda env. name used in [first step](https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md#set-up-the-conda-environment), `ss` modified to `sound_spaces` instead

At this stage, `habitat-sim` installation is incomplete as on `import`ing it in a python terminal, it throws following error:
```
>>> import habitat_sim
python: Relink `/home/$USER/anaconda3/envs/sound_spaces/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-linux-x86_64.egg/habitat_sim/_ext/libRLRAudioPropagation.so' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ModuleNotFoundError: No module named 'magnum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/$USER/anaconda3/envs/sound_spaces/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-linux-x86_64.egg/habitat_sim/__init__.py", line 13, in <module>
    import habitat_sim._ext.habitat_sim_bindings
ImportError: initialization failed
```

Please help in resolving above issue to continue with the [installation](https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md) process

**Comment by ChanganVR** [comment]
can you manually install the required numpy version and then run the installation process again?
