### ISSUE TITLE
AudioNav dataset not found

### ISSUE THREAD

**Issue by EntyccE** [facebookresearch/sound-spaces#130]
I followed the install instruction and I encounter the issue that AudioNav dataset is not found. I didn't find the solution. Where should I download it? Thanks!
Detailed Message:
```
2023-10-18 17:54:35,435 Initializing dataset AudioNav
Traceback (most recent call last):
  File "/ceph/home/zhanghaotian/multi-modal-mas/sound-spaces/scripts/interactive_demo.py", line 244, in <module>
    main()
  File "/ceph/home/zhanghaotian/multi-modal-mas/sound-spaces/scripts/interactive_demo.py", line 233, in main
    dataset = make_dataset(id_dataset=config.TASK_CONFIG.DATASET.TYPE, config=config.TASK_CONFIG.DATASET)
  File "/ceph/home/zhanghaotian/multi-modal-mas/habitat-lab/habitat/datasets/registration.py", line 21, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/ceph/home/zhanghaotian/multi-modal-mas/sound-spaces/soundspaces/datasets/audionav_dataset.py", line 86, in __init__
    with gzip.open(datasetfile_path, "rt") as f:
  File "/ceph/home/zhanghaotian/anaconda3/envs/ss/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/ceph/home/zhanghaotian/anaconda3/envs/ss/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/audionav/mp3d/v1/val_telephone/val_telephone.json.gz'
```

**Comment by ChanganVR** [comment]
you can download the dataset here: https://github.com/facebookresearch/sound-spaces/tree/main/soundspaces

**Comment by YYDreamzure** [comment]
@ChanganVR I have downloaded the datasets, metadata, pretrained_weights and sounds. However, the scene_datasets and scene_observations are not available for download. I have emailed in and submitted the Term of Use a long while ago but no one got back to me after that. I wonder how may I get the dataset or use the pretrained_weights to recreate the audionav video?

Thank you in advance!
