### ISSUE TITLE
Issue with cache observations

### ISSUE THREAD

**Issue by sun17-311** [facebookresearch/sound-spaces#134]
Hello!
I am trying to run `python scripts/cache_observations.py` by following the [https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md](url),i get this issue:
`Traceback (most recent call last):

  File "/home/sdl/Desktop/Project/soundspace/sound-spaces/scripts/cache_observations.py", line 18, in <module>
    from soundspaces.utils import load_metadata
  File "/home/sdl/Desktop/Project/soundspace/sound-spaces/soundspaces/__init__.py", line 7, in <module>
    from soundspaces.tasks.action_space import MoveOnlySpaceConfiguration
  File "/home/sdl/Desktop/Project/soundspace/sound-spaces/soundspaces/tasks/__init__.py", line 2, in <module>
    from soundspaces.simulator import SoundSpacesSim
  File "/home/sdl/Desktop/Project/soundspace/sound-spaces/soundspaces/simulator.py", line 28, in <module>
    from habitat.sims.habitat_simulator.habitat_simulator import HabitatSimSensor, overwrite_config

ImportError: cannot import name 'HabitatSimSensor' from 'habitat.sims.habitat_simulator.habitat_simulator' (/home/sdl/Desktop/Project/soundspace/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py)`
I was sure to install the specified version of habitat-lab and habitat-sim,and i had check out habitat-sim and habitat-lab both at v0.1.7.

I was wondering if anyone has ran into this before or has any ideas how to solve this?
Thanks!

**Comment by sun17-311** [comment]
I looked at habitat_simulator.py in habitat-lab v0.1.7, and there is no HabitatSimSensor class in it.
when i check out at v0.2.0,the problem was solved, but I got a new problem:
`ModuleNotFoundError: No module named 'habitat_sim.robots'`

**Comment by swapb94** [comment]
@sun17-311  Were you able to resolve this?
