### ISSUE TITLE
Issues in running interactive_demo.py

### ISSUE THREAD

**Issue by gtatiya** [facebookresearch/sound-spaces#44]
Hi @ChanganVR,

I am trying to run `python scripts/interactive_demo.py`, but I get this error:

```
(habitat) gyan@gyan-Lenovo-Y50:~/Documents/sound-spaces$ python scripts/interactive_demo.py
pygame 2.0.1 (SDL 2.0.14, Python 3.6.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 242, in <module>
    main()
  File "scripts/interactive_demo.py", line 219, in main
    run_type=args.run_type)
  File "/home/gyan/Documents/sound-spaces/ss_baselines/av_nav/config/default.py", line 177, in get_config
    config = merge_from_path(_C.clone(), config_paths)
  File "/home/gyan/Documents/sound-spaces/ss_baselines/av_nav/config/default.py", line 155, in merge_from_path
    config.merge_from_file(config_path)
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'baselines/config/audiogoal_rgb_demo.yaml'
```

When I run `python scripts/interactive_demo.py --exp-config "/home/gyan/Documents/sound-spaces/configs/audionav/av_nav/mp3d/audiogoal.yaml"`, I get this error:

```
(habitat) gyan@gyan-Lenovo-Y50:~/Documents/sound-spaces$ python scripts/interactive_demo.py --exp-config "/home/gyan/Documents/sound-spaces/configs/audionav/av_nav/mp3d/audiogoal.yaml"
pygame 2.0.1 (SDL 2.0.14, Python 3.6.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 242, in <module>
    main()
  File "scripts/interactive_demo.py", line 219, in main
    run_type=args.run_type)
  File "/home/gyan/Documents/sound-spaces/ss_baselines/av_nav/config/default.py", line 178, in get_config
    config.TASK_CONFIG = get_task_config(config_paths=config.BASE_TASK_CONFIG_PATH)
  File "/home/gyan/Documents/sound-spaces/ss_baselines/av_nav/config/default.py", line 226, in get_task_config
    config.merge_from_file(config_path)
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/tasks/pointgoal.yaml'
```
When I change `_C.BASE_TASK_CONFIG_PATH` in `ss_baselines/av_nav/config/default.py` to `configs/audionav/av_nav/mp3d/pointgoal.yaml`, I get this error:

```
VIDEO_DIR: data/models/output/video_dir
VIDEO_OPTION: ['disk', 'tensorboard']
VISUALIZATION_OPTION: ['top_down_map']
2021-06-17 15:08:59,368 Initializing dataset AudioNav
Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 242, in <module>
    main()
  File "scripts/interactive_demo.py", line 231, in main
    dataset = make_dataset(id_dataset=config.TASK_CONFIG.DATASET.TYPE, config=config.TASK_CONFIG.DATASET)
  File "/home/gyan/Documents/habitat-lab/habitat/datasets/registration.py", line 18, in make_dataset
    assert _dataset is not None, "Could not find dataset {}".format(id_dataset)
AssertionError: Could not find dataset AudioNav
```

Could you please fix these errors and help me run interactive_demo.py?

**Comment by ChanganVR** [comment]
@gtatiya I fixed the import. Can you try again?

**Comment by gtatiya** [comment]
I pulled and when I did `python scripts/interactive_demo.py`, I get this error:
```
(habitat) gyan@gyan-Lenovo-Y50:~/Documents/sound-spaces$ python scripts/interactive_demo.py
pygame 2.0.1 (SDL 2.0.14, Python 3.6.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
usage: interactive_demo.py [-h] [--run-type {train,eval}] --exp-config
                           EXP_CONFIG [--debug] [--keys KEYS]
                           ...
interactive_demo.py: error: the following arguments are required: --exp-config
```

When I did `python scripts/interactive_demo.py --exp-config "ss_baselines/av_nav/config/audionav/mp3d/interactive_demo.yaml"`, I get this error:
```
USE_SYNC_VECENV: False
USE_VECENV: True
VIDEO_DIR: data/models/output/video_dir
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
2021-06-18 08:12:19,539 Initializing dataset AudioNav
Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 243, in <module>
    main()
  File "scripts/interactive_demo.py", line 232, in main
    dataset = make_dataset(id_dataset=config.TASK_CONFIG.DATASET.TYPE, config=config.TASK_CONFIG.DATASET)
  File "/home/gyan/Documents/habitat-lab/habitat/datasets/registration.py", line 20, in make_dataset
    return _dataset(**kwargs)
  File "/home/gyan/Documents/sound-spaces/soundspaces/datasets/audionav_dataset.py", line 86, in __init__
    with gzip.open(datasetfile_path, "rt") as f:
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/audionav/mp3d/v1/test_demo/test_demo.json.gz'
```

There is no `test_demo` folder in `v1`. Could you please fix these errors and help me run interactive_demo.py?

**Comment by ChanganVR** [comment]
Hi Gyan,

I can't find the test_demo.json.gz on my end either. But this split is
nothing different from other splits. I just generated one episode for which
I wanted to generate the demo. Can you try replacing it with for example
val_telephone.json.gz?

Thanks,
Changan

**Comment by gtatiya** [comment]
Hi @ChanganVR,

I changed `test_demo` in line https://github.com/facebookresearch/sound-spaces/blob/master/ss_baselines/av_nav/config/audionav/mp3d/interactive_demo.yaml#L44 to `val_telephone`, and got this error:

```
Traceback (most recent call last):
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/librosa/core/audio.py", line 149, in load
    with sf.SoundFile(path) as sf_desc:
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'data/sounds/demo/telephone.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 243, in <module>
    main()
  File "scripts/interactive_demo.py", line 236, in main
    interactive_demo(config, env)
  File "scripts/interactive_demo.py", line 52, in interactive_demo
    observation = env.reset()
  File "/home/gyan/Documents/sound-spaces/ss_baselines/common/environments.py", line 51, in reset
    observations = super().reset()
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 354, in reset
    return self._env.reset()
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 215, in reset
    self.reconfigure(self._config)
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 293, in reconfigure
    self._sim.reconfigure(self._config.SIMULATOR)
  File "/home/gyan/Documents/sound-spaces/soundspaces/simulator.py", line 320, in reconfigure
    self._load_single_source_sound()
  File "/home/gyan/Documents/sound-spaces/soundspaces/simulator.py", line 553, in _load_single_source_sound
    sr=self.config.AUDIO.RIR_SAMPLING_RATE)
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/librosa/core/audio.py", line 166, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/librosa/core/audio.py", line 190, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/audioread/__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/audioread/rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/sounds/demo/telephone.wav'
```

I changed `data/sounds/demo` in line https://github.com/facebookresearch/sound-spaces/blob/master/configs/audionav/av_nav/mp3d/interactive_demo.yaml#L21 to `data/sounds/1s_all` and a GUI opened for half a second and then I got this error:

```
Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0x00007fbb98e80700 (most recent call first):
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/habitat_sim-0.1.6-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 433 in draw_observation
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/habitat_sim-0.1.6-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 251 in get_sensor_observations
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/habitat_sim-0.1.6-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 137 in reset
  File "/home/gyan/Documents/sound-spaces/soundspaces/simulator.py", line 418 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/embodied_task.py", line 279 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 217 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 354 in reset
  File "/home/gyan/Documents/sound-spaces/ss_baselines/common/environments.py", line 51 in reset
  File "scripts/interactive_demo.py", line 52 in interactive_demo
  File "scripts/interactive_demo.py", line 236 in main
  File "scripts/interactive_demo.py", line 243 in <module>
Aborted (core dumped)
```

If you like I can make a pull request for the changes I made as that fixed some of the errors. Could you please fix the error above and help me run interactive_demo.py?

**Comment by ChanganVR** [comment]
@gtatiya I tried to fix some bugs but since I don't have attached display, I couldn't really see what if this interative demo works at the last step. Can you try and see if it works now?

**Comment by gtatiya** [comment]
There is no changes in master branch, so I check-outed to circleci, and ran `python scripts/interactive_demo.py` and got this error:

```
Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 245, in <module>
    main()
  File "scripts/interactive_demo.py", line 235, in main
    env = AudioNavRLEnv(config=config, dataset=dataset)
  File "/home/gyan/Documents/sound-spaces/ss_baselines/common/environments.py", line 46, in __init__
    super().__init__(self._core_env_config, dataset)
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 331, in __init__
    self._env = Env(config, dataset)
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 105, in __init__
    id_sim=self._config.SIMULATOR.TYPE, config=self._config.SIMULATOR
  File "/home/gyan/Documents/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/home/gyan/Documents/sound-spaces/soundspaces/simulator.py", line 122, in __init__
    self.sim_config = self.create_sim_config(self._sensor_suite)
  File "/home/gyan/Documents/sound-spaces/soundspaces/simulator.py", line 176, in create_sim_config
    sim_config.scene_id = self.config.SCENE
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration' object has no attribute 'scene_id'
```

I changed `sim_config.scene_id` in line https://github.com/facebookresearch/sound-spaces/blob/circleci/soundspaces/simulator.py#L176 to `sim_config.scene.id` and got this error:

```
Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 245, in <module>
    main()
  File "scripts/interactive_demo.py", line 235, in main
    env = AudioNavRLEnv(config=config, dataset=dataset)
  File "/home/gyan/Documents/sound-spaces/ss_baselines/common/environments.py", line 46, in __init__
    super().__init__(self._core_env_config, dataset)
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 331, in __init__
    self._env = Env(config, dataset)
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 105, in __init__
    id_sim=self._config.SIMULATOR.TYPE, config=self._config.SIMULATOR
  File "/home/gyan/Documents/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/home/gyan/Documents/sound-spaces/soundspaces/simulator.py", line 123, in __init__
    self._current_scene = self.sim_config.sim_cfg.scene_id
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SimulatorCon' object has no attribute 'scene_id'
```

I changed `self.sim_config.sim_cfg.scene_id` in line https://github.com/facebookresearch/sound-spaces/blob/circleci/soundspaces/simulator.py#L123 to self.sim_config.sim_cfg.scene.id and again a GUI opened for half a second and then I got this error:

```
Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0x00007f35c04fe700 (most recent call first):
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/habitat_sim-0.1.6-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 433 in draw_observation
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/habitat_sim-0.1.6-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 251 in get_sensor_observations
  File "/home/gyan/miniconda3/envs/habitat/lib/python3.6/site-packages/habitat_sim-0.1.6-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 137 in reset
  File "/home/gyan/Documents/sound-spaces/soundspaces/simulator.py", line 422 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/embodied_task.py", line 279 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 217 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 354 in reset
  File "/home/gyan/Documents/sound-spaces/ss_baselines/common/environments.py", line 51 in reset
  File "scripts/interactive_demo.py", line 52 in interactive_demo
  File "scripts/interactive_demo.py", line 238 in main
  File "scripts/interactive_demo.py", line 245 in <module>
Aborted (core dumped)
```

**Comment by ChanganVR** [comment]
Oh yeah, forgot to tell you, I also updated to habitat v0.1.7 and the scene_id error was because of that.

> Fatal Python error: (pygame parachute) Segmentation Fault
I did not experience this on my end. It looks like a pygame installation issue. Can you check if pygame runs correctly on your end by for example, run a simple test program?

**Comment by gtatiya** [comment]
I tested pygame with other env. and I didn't that error. I also installed habitat v0.1.7 and ran `python scripts/interactive_demo.py` and again got this error:

```
Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0x00007f6e1062b700 (most recent call first):
  File "/home/gyan/miniconda3/envs/avn/lib/python3.6/site-packages/habitat_sim-0.1.7-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 579 in draw_observation
  File "/home/gyan/miniconda3/envs/avn/lib/python3.6/site-packages/habitat_sim-0.1.7-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 343 in get_sensor_observations
  File "/home/gyan/miniconda3/envs/avn/lib/python3.6/site-packages/habitat_sim-0.1.7-py3.6-linux-x86_64.egg/habitat_sim/simulator.py", line 173 in reset
  File "/home/gyan/Documents/sound-spaces/soundspaces/simulator.py", line 422 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/embodied_task.py", line 280 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 222 in reset
  File "/home/gyan/Documents/habitat-lab/habitat/core/env.py", line 360 in reset
  File "/home/gyan/miniconda3/envs/avn/lib/python3.6/contextlib.py", line 52 in inner
  File "/home/gyan/Documents/sound-spaces/ss_baselines/common/environments.py", line 51 in reset
  File "scripts/interactive_demo.py", line 52 in interactive_demo
  File "scripts/interactive_demo.py", line 238 in main
  File "scripts/interactive_demo.py", line 245 in <module>
Aborted (core dumped)
```

**Comment by ChanganVR** [comment]
@gtatiya I'm not exactly sure what happens here but it seems like there is an issue of using HabitatSim and Pygame together. I'm not developing HabitatSim and to further troubleshoot this issue, you need to post an issue in the HabitatSim repo.

But what you can do here is to add the command line option "TASK_CONFIG.SIMULATOR.USE_RENDERED_OBSERVATIONS True" and comment out this line of code. https://github.com/facebookresearch/sound-spaces/blob/dbc587771c26b72bf0f2d41ba4a421434579bf3a/scripts/interactive_demo.py#L224

This removes the top-down map and only uses the prerendered visual. Hopefully it can work to some degree. Again, I don't have an attached display so let me know how it works.

**Comment by gtatiya** [comment]
Hi @ChanganVR, I did what you suggested, and now I do not get any error, but after I run `python scripts/interactive_demo.py`, the code gets stuck and does nothing.

Here's the screenshot:
![image](https://user-images.githubusercontent.com/22827159/123864431-c1cf2800-d8f8-11eb-9a42-615d2858805e.png)

**Comment by ChanganVR** [comment]
Did you enter a commnd key w/a/d/f? This pygame concole receives a command, interacts with the environment and displays the image. If you still do not see anything, you can switch to matplotlib to plot the observation image interactively or save the received frame to local every step.

**Comment by gtatiya** [comment]
I tried pressing those keys, but still nothing happens. Here's a screen shot:
![image](https://user-images.githubusercontent.com/22827159/124140641-a67a2f00-da56-11eb-82da-f342ca3bb8a6.png)

Could you please point me to the changes to make to switch to matplotlib to plot?

**Comment by ChanganVR** [comment]
The easiest way is just to plot the new observation on a new figure at each step and close it when you press the key. This function should be relatively easy to write. Unfortunately, I don't have attached display currently for testing so I can't help with writing the code.

**Comment by gtatiya** [comment]
I was pressing keys on the terminal. When I tried to press keys on the GUI "Interactive Demo", it worked and I was able to control the agent. I wanted to also play audio, so I un-commented this code from line: https://github.com/facebookresearch/sound-spaces/blob/master/scripts/interactive_demo.py#L108 to line 114 and also imported `from scipy.io import wavfile`, but now I am getting this error:
```
Traceback (most recent call last):
  File "scripts/interactive_demo.py", line 247, in <module>
    main()
  File "scripts/interactive_demo.py", line 240, in main
    interactive_demo(config, env)
  File "scripts/interactive_demo.py", line 115, in interactive_demo
    pygame.mixer.music.load(temp_file)
pygame.error: Invalid source channels
```
Could you please fix this?

**Comment by ChanganVR** [comment]
Were you able to see the agent moving visually? 

Did you uncomment both lines here?
https://github.com/facebookresearch/sound-spaces/blob/1e2e8a35f4a205639778d9d77044c699637a4085/scripts/interactive_demo.py#L111-L112

I forgot which one worked for me, but it's either L111 or L112.

**Comment by gtatiya** [comment]
Yes, I was able to see the agent moving visually. The audio also worked, when I commented `wavfile.write(temp_file, sr, audio.T)` and used `wavfile.write(temp_file, sr, audio)`. Maybe you can push this: https://github.com/facebookresearch/sound-spaces/issues/44#issuecomment-869233256, and remove `wavfile.write(temp_file, sr, audio.T)` and also mentioned in the README that GUI must be selected/active while pressing the keys. Thanks for fixing this issue.

**Comment by ChanganVR** [comment]
No problem and thanks for letting me know. I'm glad that it finally worked!

**Comment by gtatiya** [comment]
Thanks, I saw that you pushed a change to fix this issue, but there are a few more changes needed:
- Comment `config.TASK_CONFIG.TASK.MEASUREMENTS.append("TOP_DOWN_MAP")` in line: https://github.com/facebookresearch/sound-spaces/blob/master/scripts/interactive_demo.py#L223.
- Make `USE_RENDERED_OBSERVATIONS` to True in line: https://github.com/facebookresearch/sound-spaces/blob/master/configs/audionav/av_nav/mp3d/interactive_demo.yaml#L16.
- In https://github.com/facebookresearch/sound-spaces/blob/master/scripts/interactive_demo.py import `from scipy.io import wavfile`.

**Comment by ChanganVR** [comment]
Thanks for the feedback! I didn't make changes to these lines because I wasn't sure if the issue was becuase of your pygame installation or the incompatability between habitat-sim and pygame and it worked for me when I had an attached display. If other people raise the same issue later, I'll make these changes.
