### ISSUE TITLE
Segmentation fault (core dumped) when running env.reset()

### ISSUE THREAD

**Issue by YHWmz** [facebookresearch/sound-spaces#81]
Hello,

I'm trying to train a continuous navigation agent with SoundSpaces2.0. However, I met an error when trying to execute the baseline on replica
```
python ss_baselines/av_nav/run.py --exp-config ss_baselines/av_nav/config/audionav/replica/train_telephone/audiogoal_depth_ddppo.yaml --model-dir data/models/ss2/replica/dav_nav CONTINUOUS True
```

```
[15:28:19:640656]:[Sensor] AudioSensor.cpp(126)::runSimulation : [Audio]  Loading semantic scene
[15:28:19:640671]:[Sensor] AudioSensor.cpp(293)::loadSemanticMesh : [Audio]  Loading semantic mesh
Traceback (most recent call last):
  File "ss_baselines/av_nav/run.py", line 101, in <module>
    main()
  File "ss_baselines/av_nav/run.py", line 95, in main
    trainer.train()
  File "/root/sound-spaces/ss_baselines/av_nav/ddppo/ddppo_trainer.py", line 166, in train
    observations = self.envs.reset()
  File "/root/habitat-lab/habitat/core/vector_env.py", line 376, in reset
    results.append(read_fn())
  File "/root/habitat-lab/habitat/core/vector_env.py", line 102, in __call__
    res = self.read_fn()
  File "/root/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Exception ignored in: <function VectorEnv.__del__ at 0x7f464558a8c8>
Traceback (most recent call last):
  File "/root/habitat-lab/habitat/core/vector_env.py", line 576, in __del__
    self.close()
  File "/root/habitat-lab/habitat/core/vector_env.py", line 444, in close
    read_fn()
  File "/root/habitat-lab/habitat/core/vector_env.py", line 102, in __call__
    res = self.read_fn()
  File "/root/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 
```

According to the output, I speculate that it is the problem of `self.envs.reset()`,so I write a [test.py.zip](https://github.com/facebookresearch/sound-spaces/files/9157248/test.py.zip) to verify this. The output is as follow.

```
[15:43:08:351916]:[Sensor] AudioSensor.cpp(90)::setAudioListenerTransform : [Audio]  Setting the agent transform : position [ Vector(3.14562, 0.0389276, -5.61576) ], rotQuat[ Vector(1, 0, 2.45858e-05, 0) ]
[15:43:08:351975]:[Sensor] AudioSensor.cpp(278)::createAudioSimulator : [Audio]  Create audio simulator iteration:  0
[15:43:08:352394]:[Sensor] AudioSensor.cpp(114)::runSimulation : [Audio]  Running the audio simulator
[15:43:08:352415]:[Sensor] AudioSensor.cpp(119)::runSimulation : [Audio]  New initialization, will upload geometry and add the source at position :  Vector(3.05865, -0.159589, -4.38473)
[15:43:08:352433]:[Sensor] AudioSensor.cpp(126)::runSimulation : [Audio]  Loading semantic scene
[15:43:08:352447]:[Sensor] AudioSensor.cpp(293)::loadSemanticMesh : [Audio]  Loading semantic mesh
Segmentation fault (core dumped)
```

In a word, a Segmentation fault occurs when executing `AudioNavRLEnv.reset()`. 
Do anyone know how to resolve this? Any help will be appreciated.

(I have successfully run the example script of habitat-lab, so I believe that it is not the problem of it)

# System Info
OS : linux Debian 10
Python version: Python 3.7.7
habitat-lab, habitat-sim: 0.2.2

**Comment by ChanganVR** [comment]
@YHWmz  which example scrip of habitat-lab did you run? Could you try running this script? https://github.com/facebookresearch/habitat-sim/blob/main/examples/tutorials/audio_agent.py

**Comment by YHWmz** [comment]
@ChanganVR I have run the habitat-lab/examples/example.py.  

I will try to run [audio_agent.py](https://github.com/facebookresearch/habitat-sim/blob/main/examples/tutorials/audio_agent.py) and let you know once the result is out.

**Comment by YHWmz** [comment]
@ChanganVR I can run the [audio_agent.py](https://github.com/facebookresearch/habitat-sim/blob/main/examples/tutorials/audio_agent.py) script, and the output is as follow.
```
......4235754e-10, 2.027423923189886e-10, 2.115267405677912e-10, 2.2001325761245027e-10, 2.2805723975949377e-10, 2.3552315653319056e-10, 2.4228685724381194e-10, 2.4823798572271016e-10, 2.532820064793384e-10, 2.573422586138463e-10, 2.603623983077341e-10]]
End Time : 
Current Time = 18:17:29
[18:17:29:408606]:[Physics] PhysicsManager.cpp(50)::~PhysicsManager : Deconstructing PhysicsManager
[18:17:29:408697]:[Scene] SceneManager.h(25)::~SceneManager : Deconstructing SceneManager
[18:17:29:408708]:[Scene] SceneGraph.h(25)::~SceneGraph : Deconstructing SceneGraph
[18:17:29:408815]:[Sensor] AudioSensor.cpp(68)::~AudioSensor : [Audio]  Destroying the audio sensor
[18:17:29:439390]:[Sensor] Sensor.cpp(69)::~Sensor : Deconstructing Sensor
[18:17:29:439450]:[Scene] SceneGraph.h(25)::~SceneGraph : Deconstructing SceneGraph
[18:17:29:439643]:[Scene] SemanticScene.h(47)::~SemanticScene : Deconstructing SemanticScene
[18:17:29:442568]:[Sim] Simulator.cpp(66)::~Simulator : Deconstructing Simulator
```
I think I got the proper output, do I?

When I use mp3d instead of replica, there is no segmentation fault anymore... Maybe there are some problems with my config of replica. Anyway, thank you for your reply~

However, I met a new error about multiprocess when running the DDPPO baseline on mp3d. I think I need to open a new issue to describe it.

**Comment by ChanganVR** [comment]
@YHWmz yeah, that looks about right to me. The segmentation issue you run into with Replica might have something to do with its semantic annotations. Could your disable using materials in the acoustics config and rerun Replica?

**Comment by YHWmz** [comment]
@ChanganVR Hi, did you mean to set the ```acoustics_config.enableMaterials = False``` in ```simulator.py```?

**Comment by ChanganVR** [comment]
yes, please try that.

**Comment by YHWmz** [comment]
It seems that didn't work...

**Comment by YHWmz** [comment]
The output is the same as before

**Comment by ChanganVR** [comment]
for the sake of debugging, you should just use audio_agent.py. Also, if the output is the same and you are still seeing "loadSemanticMesh : [Audio]  Loading semantic mesh", then the simulator is still loading semantic annotation for material rendering.

**Comment by YHWmz** [comment]
Okay, I will try to debug it latter and let you know once the code works on replica. Thank you for your help again~

**Comment by 2206411193** [comment]
> @ChanganVR Hi, did you mean to set the `acoustics_config.enableMaterials = False` in `simulator.py`?



> for the sake of debugging, you should just use audio_agent.py. Also, if the output is the same and you are still seeing "loadSemanticMesh : [Audio] Loading semantic mesh", then the simulator is still loading semantic annotation for material rendering.

Hi @ChanganVR , I got a same error, but  when I set `acoustics_config.enableMaterials = False`,the abort error is not appear in Habitat-Sim.
the following is the `python audio_agent.py ` result
```
[21:20:53:301649]:[Physics] PhysicsManager.cpp(50)::~PhysicsManager : Deconstructing PhysicsManager
[21:20:53:302652]:[Scene] SceneManager.h(25)::~SceneManager : Deconstructing SceneManager
[21:20:53:302688]:[Scene] SceneGraph.h(25)::~SceneGraph : Deconstructing SceneGraph
[21:20:53:303013]:[Sensor] AudioSensor.cpp(68)::~AudioSensor : [Audio]  Destroying the audio sensor
[21:20:53:305718]:[Sensor] Sensor.cpp(69)::~Sensor : Deconstructing Sensor
[21:20:53:305868]:[Scene] SemanticScene.h(47)::~SemanticScene : Deconstructing SemanticScene
[21:20:53:308001]:[Sim] Simulator.cpp(66)::~Simulator : Deconstructing Simulator
```
but When I run `python  ss_baselines/av_nav/run.py --exp-config ss_baselines/av_nav/config/audionav/replica/train_telephone/audiogoal_depth.yaml --model-dir data/models/ss2/replica/dav_nav CONTINUOUS True`
An error occur:
```
[21:26:22:122470]:[Sensor] AudioSensor.cpp(126)::runSimulation : [Audio]  Loading semantic scene
[21:26:22:122496]:[Sensor] AudioSensor.cpp(293)::loadSemanticMesh : [Audio]  Loading semantic mesh
Traceback (most recent call last):
  File "/ssdhome/qzb521/qinghua/sound-spaces/ss_baselines/av_nav/run.py", line 105, in <module>
    main()
  File "/ssdhome/qzb521/qinghua/sound-spaces/ss_baselines/av_nav/run.py", line 99, in main
    trainer.train()
  File "/ssdhome/qzb521/qinghua/sound-spaces/ss_baselines/av_nav/ppo/ppo_trainer.py", line 263, in train
    observations = self.envs.reset()
  File "/ssdhome/qzb521/qinghua/habitat-lab/habitat/core/vector_env.py", line 384, in reset
    results.append(read_fn())
  File "/ssdhome/qzb521/qinghua/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/ssdhome/qzb521/qinghua/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 67, in recv
    buf = self.recv_bytes()
  File "/home/qzb521/miniconda3/envs/qinghua/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/qzb521/miniconda3/envs/qinghua/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/qzb521/miniconda3/envs/qinghua/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
Exception ignored in: <function VectorEnv.__del__ at 0x7fe14b417dc0>
Traceback (most recent call last):
  File "/ssdhome/qzb521/qinghua/habitat-lab/habitat/core/vector_env.py", line 592, in __del__
    self.close()
  File "/ssdhome/qzb521/qinghua/habitat-lab/habitat/core/vector_env.py", line 460, in close
    read_fn()
  File "/ssdhome/qzb521/qinghua/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/ssdhome/qzb521/qinghua/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 67, in recv
    buf = self.recv_bytes()
  File "/home/qzb521/miniconda3/envs/qinghua/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/qzb521/miniconda3/envs/qinghua/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/qzb521/miniconda3/envs/qinghua/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError: 
```
Could  you give me some help to solve it? thanks a lot.
